[package]
name = "tunapanel"
version = "0.1.0"
authors = ["Keegan McAllister <mcallister.keegan@gmail.com>"]

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
hyper = "0.10"
error-chain = "0.10"
log = "0.3"
env_logger = "0.4"
handlebars = "0.26"
lazy_static = "0.2"
